### PR TITLE
Hf/add player velosity to projectiles

### PR DESCRIPTION
**Pull request by tofb15**

### CODE REVIEW

**Comment by whalemane** [comment]
This is related to #400

**Comment by Piratkopia13** [comment]
Make sure to test if aiming is even more difficult now (if that is even possible).
Adding the player velocity will make the projectiles not land where the player was aiming if he was moving while shooting.

**Comment by whalemane** [comment]
This does not solve the #400, still extinguishes the candle if you shoot and strafe to the right

**Comment by viktor4006094** [comment]
Now solves #400
Player can shot their own candle if it's on the floor but not if it's in their hand.
Also fixed a bug related to the movement in debug when the framerate is low

**Pull request merged**
